//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemGestionBuses {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResEnglish() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemGestionBuses.ResEnglish", typeof(ResEnglish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save and continue.
        /// </summary>
        internal static string btnfinalizar {
            get {
                return ResourceManager.GetString("btnfinalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation Code.
        /// </summary>
        internal static string codigoconfir {
            get {
                return ResourceManager.GetString("codigoconfir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm the password.
        /// </summary>
        internal static string confirmacion_contra {
            get {
                return ResourceManager.GetString("confirmacion_contra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password and PIN.
        /// </summary>
        internal static string contra_pin {
            get {
                return ResourceManager.GetString("contra_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string contrasena {
            get {
                return ResourceManager.GetString("contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        internal static string informacion {
            get {
                return ResourceManager.GetString("informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the data.
        /// </summary>
        internal static string ingresadatos {
            get {
                return ResourceManager.GetString("ingresadatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipality.
        /// </summary>
        internal static string municipiolbl {
            get {
                return ResourceManager.GetString("municipiolbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot Password?.
        /// </summary>
        internal static string olvido_contrasena {
            get {
                return ResourceManager.GetString("olvido_contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Step 1.
        /// </summary>
        internal static string paso1 {
            get {
                return ResourceManager.GetString("paso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string paso1btn {
            get {
                return ResourceManager.GetString("paso1btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the main e-mail to manage the system..
        /// </summary>
        internal static string paso1lbl1 {
            get {
                return ResourceManager.GetString("paso1lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your username..
        /// </summary>
        internal static string paso1lbl2 {
            get {
                return ResourceManager.GetString("paso1lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Step 2.
        /// </summary>
        internal static string paso2 {
            get {
                return ResourceManager.GetString("paso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend the code..
        /// </summary>
        internal static string paso2btn1 {
            get {
                return ResourceManager.GetString("paso2btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Code.
        /// </summary>
        internal static string paso2btn2 {
            get {
                return ResourceManager.GetString("paso2btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the confirmation code we sent to your e-mail account, to confirm your identity.
        /// </summary>
        internal static string paso2lbl1 {
            get {
                return ResourceManager.GetString("paso2lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Step 3.
        /// </summary>
        internal static string paso3 {
            get {
                return ResourceManager.GetString("paso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string paso3btn {
            get {
                return ResourceManager.GetString("paso3btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password has to contains a minimum of 10  characters, with a combination of letters and numbers.(Just some special characters are allowed).
        /// </summary>
        internal static string paso3lbl1 {
            get {
                return ResourceManager.GetString("paso3lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Step 4.
        /// </summary>
        internal static string paso4 {
            get {
                return ResourceManager.GetString("paso4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string paso4btn {
            get {
                return ResourceManager.GetString("paso4btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the name of your enterprise, instituttion, entrepreneurship or bussines..
        /// </summary>
        internal static string paso4lbl1 {
            get {
                return ResourceManager.GetString("paso4lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the adress where is located.
        /// </summary>
        internal static string paso4lbl2 {
            get {
                return ResourceManager.GetString("paso4lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone number.
        /// </summary>
        internal static string phonelbl {
            get {
                return ResourceManager.GetString("phonelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a PIN of security. (Minimum 10 characters).
        /// </summary>
        internal static string pinlabel {
            get {
                return ResourceManager.GetString("pinlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        internal static string sesion {
            get {
                return ResourceManager.GetString("sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
    }
}
