//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemGestionBuses.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemGestionBuses.Idiomas.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string btnActualizarCliente {
            get {
                return ResourceManager.GetString("btnActualizarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Grid.
        /// </summary>
        internal static string btnActualizarGrid {
            get {
                return ResourceManager.GetString("btnActualizarGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar grid de datos.
        /// </summary>
        internal static string btnActualizarGriddedatos {
            get {
                return ResourceManager.GetString("btnActualizarGriddedatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar grid de datos.
        /// </summary>
        internal static string btnActualizarGridMan {
            get {
                return ResourceManager.GetString("btnActualizarGridMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Unidad.
        /// </summary>
        internal static string btnActualizarUnidad {
            get {
                return ResourceManager.GetString("btnActualizarUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Viaje.
        /// </summary>
        internal static string btnActualizarViaje {
            get {
                return ResourceManager.GetString("btnActualizarViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Grid.
        /// </summary>
        internal static string btnActulizarGrid {
            get {
                return ResourceManager.GetString("btnActulizarGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar clientes.
        /// </summary>
        internal static string btnAgregarClientes {
            get {
                return ResourceManager.GetString("btnAgregarClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Conductor.
        /// </summary>
        internal static string btnAgregarConductor {
            get {
                return ResourceManager.GetString("btnAgregarConductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Direccion.
        /// </summary>
        internal static string btnAgregarDireccion {
            get {
                return ResourceManager.GetString("btnAgregarDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Empleado.
        /// </summary>
        internal static string btnAgregarEmpleado {
            get {
                return ResourceManager.GetString("btnAgregarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Mantenimiento.
        /// </summary>
        internal static string btnAgregarMan {
            get {
                return ResourceManager.GetString("btnAgregarMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Punto.
        /// </summary>
        internal static string btnAgregarPunto {
            get {
                return ResourceManager.GetString("btnAgregarPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Unidad.
        /// </summary>
        internal static string btnAgregarUnidad {
            get {
                return ResourceManager.GetString("btnAgregarUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar Direcciones.
        /// </summary>
        internal static string btnAsignarDirecciones {
            get {
                return ResourceManager.GetString("btnAsignarDirecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar Viaje.
        /// </summary>
        internal static string BtnAsignarViaje {
            get {
                return ResourceManager.GetString("BtnAsignarViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar viaje.
        /// </summary>
        internal static string btnAsignarViajeCliente {
            get {
                return ResourceManager.GetString("btnAsignarViajeCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Idioma:.
        /// </summary>
        internal static string btnCambiarIdioma {
            get {
                return ResourceManager.GetString("btnCambiarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conectar.
        /// </summary>
        internal static string btnConectar {
            get {
                return ResourceManager.GetString("btnConectar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string btnConfirmar {
            get {
                return ResourceManager.GetString("btnConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string btnconfirmarcontraseñaLocus {
            get {
                return ResourceManager.GetString("btnconfirmarcontraseñaLocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Identidad.
        /// </summary>
        internal static string btnConfirmarIdentidad {
            get {
                return ResourceManager.GetString("btnConfirmarIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string btnConfirmarPINLocus {
            get {
                return ResourceManager.GetString("btnConfirmarPINLocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacta al Administrador.
        /// </summary>
        internal static string btnContactaAdmin {
            get {
                return ResourceManager.GetString("btnContactaAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Viaje.
        /// </summary>
        internal static string btnCrearViaje {
            get {
                return ResourceManager.GetString("btnCrearViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar cliente.
        /// </summary>
        internal static string btnEliminarCliente {
            get {
                return ResourceManager.GetString("btnEliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Conductor.
        /// </summary>
        internal static string btnEliminarConductor {
            get {
                return ResourceManager.GetString("btnEliminarConductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Empleado.
        /// </summary>
        internal static string btnEliminarEmpleado {
            get {
                return ResourceManager.GetString("btnEliminarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Mantenimiento.
        /// </summary>
        internal static string btnEliminarMan {
            get {
                return ResourceManager.GetString("btnEliminarMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Punto.
        /// </summary>
        internal static string btnEliminarPunto {
            get {
                return ResourceManager.GetString("btnEliminarPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Unidad.
        /// </summary>
        internal static string btnEliminarUnidad {
            get {
                return ResourceManager.GetString("btnEliminarUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Viaje.
        /// </summary>
        internal static string btnEliminarViaje {
            get {
                return ResourceManager.GetString("btnEliminarViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        internal static string btnFinalizar {
            get {
                return ResourceManager.GetString("btnFinalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Rutas.
        /// </summary>
        internal static string btnGenerarRutas {
            get {
                return ResourceManager.GetString("btnGenerarRutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string btnIniciarSesion {
            get {
                return ResourceManager.GetString("btnIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Campos.
        /// </summary>
        internal static string btnLimpiarCampos {
            get {
                return ResourceManager.GetString("btnLimpiarCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Campos.
        /// </summary>
        internal static string btnLimpiarCamposunidades {
            get {
                return ResourceManager.GetString("btnLimpiarCamposunidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Conductor.
        /// </summary>
        internal static string btnModificarConductor {
            get {
                return ResourceManager.GetString("btnModificarConductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Empleado.
        /// </summary>
        internal static string btnModificarEmpleado {
            get {
                return ResourceManager.GetString("btnModificarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Mantenimiento.
        /// </summary>
        internal static string btnModificarMan {
            get {
                return ResourceManager.GetString("btnModificarMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar por PIN de seguridad.
        /// </summary>
        internal static string btnPINdeSeguridad {
            get {
                return ResourceManager.GetString("btnPINdeSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar por Correo.
        /// </summary>
        internal static string btnRecuperaCorreo {
            get {
                return ResourceManager.GetString("btnRecuperaCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar código.
        /// </summary>
        internal static string btnReenviar {
            get {
                return ResourceManager.GetString("btnReenviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Idioma:.
        /// </summary>
        internal static string btnSeleccionarIdioma {
            get {
                return ResourceManager.GetString("btnSeleccionarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver conductores.
        /// </summary>
        internal static string btnVerConductores {
            get {
                return ResourceManager.GetString("btnVerConductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string hola {
            get {
                return ResourceManager.GetString("hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        internal static string lblAcciones {
            get {
                return ResourceManager.GetString("lblAcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de conductores.
        /// </summary>
        internal static string lblAdminConductores {
            get {
                return ResourceManager.GetString("lblAdminConductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de Empleados.
        /// </summary>
        internal static string lblAdministraicionEmpleados {
            get {
                return ResourceManager.GetString("lblAdministraicionEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año de la unidad:.
        /// </summary>
        internal static string lblAnioVehiculo {
            get {
                return ResourceManager.GetString("lblAnioVehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos del empleado.
        /// </summary>
        internal static string lblApellidoEmpleado {
            get {
                return ResourceManager.GetString("lblApellidoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string lblApellidos {
            get {
                return ResourceManager.GetString("lblApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignación de viajes..
        /// </summary>
        internal static string lblAsignaciondeViaje {
            get {
                return ResourceManager.GetString("lblAsignaciondeViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controla las acciones que te han sido asignadas a través de este panel de control..
        /// </summary>
        internal static string lblBienvenido {
            get {
                return ResourceManager.GetString("lblBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a Locus System.
        /// </summary>
        internal static string lblBienvenidoLocus {
            get {
                return ResourceManager.GetString("lblBienvenidoLocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacidad de la unidad:.
        /// </summary>
        internal static string lblCapacidadUnidad {
            get {
                return ResourceManager.GetString("lblCapacidadUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        internal static string lblCargo {
            get {
                return ResourceManager.GetString("lblCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente:.
        /// </summary>
        internal static string lblCliente {
            get {
                return ResourceManager.GetString("lblCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string lblClientes {
            get {
                return ResourceManager.GetString("lblClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente:.
        /// </summary>
        internal static string lblClienteViajes {
            get {
                return ResourceManager.GetString("lblClienteViajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de confirmación.
        /// </summary>
        internal static string lblCodConfirmacion {
            get {
                return ResourceManager.GetString("lblCodConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de confirmación que se te enció al correo para confirmar la identidad..
        /// </summary>
        internal static string lblCodigo {
            get {
                return ResourceManager.GetString("lblCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de confirmación.
        /// </summary>
        internal static string lblCodigodeConf {
            get {
                return ResourceManager.GetString("lblCodigodeConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conductor Asignado:.
        /// </summary>
        internal static string lblConductorAsignado {
            get {
                return ResourceManager.GetString("lblConductorAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1- Cambia tu Contraseña.
        /// </summary>
        internal static string lblConfigurarContraseña {
            get {
                return ResourceManager.GetString("lblConfigurarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, configura tu perfil antes de iniciar sesión.
        /// </summary>
        internal static string lblconfigurarPerfil {
            get {
                return ResourceManager.GetString("lblconfigurarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2- Configura tu pin de seguridad.
        /// </summary>
        internal static string lblConfigurarPIN {
            get {
                return ResourceManager.GetString("lblConfigurarPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de contraseña:.
        /// </summary>
        internal static string lblConfirmacionContra {
            get {
                return ResourceManager.GetString("lblConfirmacionContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña:.
        /// </summary>
        internal static string lblConfirmarContra {
            get {
                return ResourceManager.GetString("lblConfirmarContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lblContraseña {
            get {
                return ResourceManager.GetString("lblContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contenercomo mínimo 10 caracteres, con una combinación de letras y números. (Solo algunos símbolos son permitidos).
        /// </summary>
        internal static string lblContraseñaCondiciones {
            get {
                return ResourceManager.GetString("lblContraseñaCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lblContraseñaUsuario {
            get {
                return ResourceManager.GetString("lblContraseñaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña y PIN.
        /// </summary>
        internal static string lblContraseñayPin {
            get {
                return ResourceManager.GetString("lblContraseñayPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el correo principal para gestionar el sistema.
        /// </summary>
        internal static string lblcorreo {
            get {
                return ResourceManager.GetString("lblcorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string lblCorreoClientes {
            get {
                return ResourceManager.GetString("lblCorreoClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string lblDescripcion {
            get {
                return ResourceManager.GetString("lblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino adicional:.
        /// </summary>
        internal static string lblDestinoAdicional {
            get {
                return ResourceManager.GetString("lblDestinoAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino final del viaje:.
        /// </summary>
        internal static string lblDestinoFinalViaje {
            get {
                return ResourceManager.GetString("lblDestinoFinalViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa la dirección donde se encuentra:.
        /// </summary>
        internal static string lblDireccion {
            get {
                return ResourceManager.GetString("lblDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección adicional:.
        /// </summary>
        internal static string lblDireccionAdicional {
            get {
                return ResourceManager.GetString("lblDireccionAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion.
        /// </summary>
        internal static string lblDireccionClientes {
            get {
                return ResourceManager.GetString("lblDireccionClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección final:.
        /// </summary>
        internal static string lblDireccionFinal {
            get {
                return ResourceManager.GetString("lblDireccionFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DUI:.
        /// </summary>
        internal static string lblDUI {
            get {
                return ResourceManager.GetString("lblDUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el DUI correspondiente:.
        /// </summary>
        internal static string lblDUICo {
            get {
                return ResourceManager.GetString("lblDUICo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        internal static string lblEmpleados {
            get {
                return ResourceManager.GetString("lblEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el nombre de tu empresa, institución, emprendimiento o negocio..
        /// </summary>
        internal static string lblEmpresa {
            get {
                return ResourceManager.GetString("lblEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string lblEstado {
            get {
                return ResourceManager.GetString("lblEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de la unidad:.
        /// </summary>
        internal static string lblEstadoUnidad {
            get {
                return ResourceManager.GetString("lblEstadoUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del viaje:.
        /// </summary>
        internal static string lblEstadoViaje {
            get {
                return ResourceManager.GetString("lblEstadoViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        internal static string lblFecha {
            get {
                return ResourceManager.GetString("lblFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de inicio del viaje:.
        /// </summary>
        internal static string lblFechaInicioViaje {
            get {
                return ResourceManager.GetString("lblFechaInicioViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de exporación de la licencia:.
        /// </summary>
        internal static string lblFechaLimiteLicencia {
            get {
                return ResourceManager.GetString("lblFechaLimiteLicencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de retorno del viaje:.
        /// </summary>
        internal static string lblFecharetornoViaje {
            get {
                return ResourceManager.GetString("lblFecharetornoViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar por nombre.
        /// </summary>
        internal static string lblFiltrarporNombre {
            get {
                return ResourceManager.GetString("lblFiltrarporNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genero.
        /// </summary>
        internal static string lblGenero {
            get {
                return ResourceManager.GetString("lblGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Conduc:.
        /// </summary>
        internal static string lblIDconductor {
            get {
                return ResourceManager.GetString("lblIDconductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Empl:.
        /// </summary>
        internal static string lblIDempleado {
            get {
                return ResourceManager.GetString("lblIDempleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Mantenimiento.
        /// </summary>
        internal static string lblIDMan {
            get {
                return ResourceManager.GetString("lblIDMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID de la unidad.
        /// </summary>
        internal static string lblIDunidad {
            get {
                return ResourceManager.GetString("lblIDunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID del viaje.
        /// </summary>
        internal static string lblIDViaje {
            get {
                return ResourceManager.GetString("lblIDViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de confirmación que se te envió al correo para confirmar tu identidad..
        /// </summary>
        internal static string lblIndicacionesCodigoConf {
            get {
                return ResourceManager.GetString("lblIndicacionesCodigoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu usuario y haz click sobre la opción que escoges para recuperar tu contraseña.
        /// </summary>
        internal static string lblIndicacionesMetodoRec {
            get {
                return ResourceManager.GetString("lblIndicacionesMetodoRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tu nueva contraseña y haz click en confirmar para guardar los cambios..
        /// </summary>
        internal static string lblIndicacionesNuevaContra {
            get {
                return ResourceManager.GetString("lblIndicacionesNuevaContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string lblInformacion {
            get {
                return ResourceManager.GetString("lblInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa los datos.
        /// </summary>
        internal static string lblIngresaDatos {
            get {
                return ResourceManager.GetString("lblIngresaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa las direcciones:.
        /// </summary>
        internal static string lblIngresaDirecciones {
            get {
                return ResourceManager.GetString("lblIngresaDirecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia Sesión.
        /// </summary>
        internal static string lblIniciarSesion {
            get {
                return ResourceManager.GetString("lblIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud:.
        /// </summary>
        internal static string lblLatitud {
            get {
                return ResourceManager.GetString("lblLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia:.
        /// </summary>
        internal static string lblLicencia {
            get {
                return ResourceManager.GetString("lblLicencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        internal static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud:.
        /// </summary>
        internal static string lblLongitud {
            get {
                return ResourceManager.GetString("lblLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimientos.
        /// </summary>
        internal static string lblMantenimiento {
            get {
                return ResourceManager.GetString("lblMantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimientos.
        /// </summary>
        internal static string lblMantenimientos {
            get {
                return ResourceManager.GetString("lblMantenimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca de la unidad:.
        /// </summary>
        internal static string lblMarca {
            get {
                return ResourceManager.GetString("lblMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Método de recuperación.
        /// </summary>
        internal static string lblMetododerec {
            get {
                return ResourceManager.GetString("lblMetododerec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo de la unidad:.
        /// </summary>
        internal static string lblModelo {
            get {
                return ResourceManager.GetString("lblModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto del mantenimiento:.
        /// </summary>
        internal static string lblMontoMan {
            get {
                return ResourceManager.GetString("lblMontoMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        internal static string lblMunicipio {
            get {
                return ResourceManager.GetString("lblMunicipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NIT:.
        /// </summary>
        internal static string lblNIT {
            get {
                return ResourceManager.GetString("lblNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el NIT correspondiente:.
        /// </summary>
        internal static string lblNITCo {
            get {
                return ResourceManager.GetString("lblNITCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Conductor.
        /// </summary>
        internal static string lblNombreConductor {
            get {
                return ResourceManager.GetString("lblNombreConductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del empleado.
        /// </summary>
        internal static string lblNombreEmpleado {
            get {
                return ResourceManager.GetString("lblNombreEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        internal static string lblNombres {
            get {
                return ResourceManager.GetString("lblNombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un nombre de usuario.
        /// </summary>
        internal static string lblNombreUsuario {
            get {
                return ResourceManager.GetString("lblNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del viaje:.
        /// </summary>
        internal static string lblNombreViaje {
            get {
                return ResourceManager.GetString("lblNombreViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del viaje:.
        /// </summary>
        internal static string lblNombreViajePrincipal {
            get {
                return ResourceManager.GetString("lblNombreViajePrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña:.
        /// </summary>
        internal static string lblNuevaContra {
            get {
                return ResourceManager.GetString("lblNuevaContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        internal static string lblNuevaContraseña {
            get {
                return ResourceManager.GetString("lblNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero cel.
        /// </summary>
        internal static string lblNumerocel {
            get {
                return ResourceManager.GetString("lblNumerocel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de chasis.
        /// </summary>
        internal static string lblNumeroChasis {
            get {
                return ResourceManager.GetString("lblNumeroChasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de motor.
        /// </summary>
        internal static string lblNumeroMotor {
            get {
                return ResourceManager.GetString("lblNumeroMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ó.
        /// </summary>
        internal static string lblO {
            get {
                return ResourceManager.GetString("lblO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 1.
        /// </summary>
        internal static string lblPaso1 {
            get {
                return ResourceManager.GetString("lblPaso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 2.
        /// </summary>
        internal static string lblPaso2 {
            get {
                return ResourceManager.GetString("lblPaso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 3.
        /// </summary>
        internal static string lblPaso3 {
            get {
                return ResourceManager.GetString("lblPaso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 4.
        /// </summary>
        internal static string lblPaso4 {
            get {
                return ResourceManager.GetString("lblPaso4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el PIN de seguridad:.
        /// </summary>
        internal static string lblPINsec {
            get {
                return ResourceManager.GetString("lblPINsec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un PIN de seguridad. (Mínimo de 10 caracteres)..
        /// </summary>
        internal static string lblPINseguridad {
            get {
                return ResourceManager.GetString("lblPINseguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matrícula/ Placa:.
        /// </summary>
        internal static string lblPlaca {
            get {
                return ResourceManager.GetString("lblPlaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto de partida:.
        /// </summary>
        internal static string lblPuntodePartida {
            get {
                return ResourceManager.GetString("lblPuntodePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto de referencia:.
        /// </summary>
        internal static string lblPuntoReferencia {
            get {
                return ResourceManager.GetString("lblPuntoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recupera tu contraseña.
        /// </summary>
        internal static string lblRecuperarContra {
            get {
                return ResourceManager.GetString("lblRecuperarContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recupera tu cuenta.
        /// </summary>
        internal static string lblRecuperatucuenta {
            get {
                return ResourceManager.GetString("lblRecuperatucuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        internal static string lblReportes {
            get {
                return ResourceManager.GetString("lblReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona el viaje que deseas asignarle al cliente..
        /// </summary>
        internal static string lblSeleccionViaje {
            get {
                return ResourceManager.GetString("lblSeleccionViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarifa:.
        /// </summary>
        internal static string lblTarifa {
            get {
                return ResourceManager.GetString("lblTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string lblTeléfono {
            get {
                return ResourceManager.GetString("lblTeléfono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono del empleado.
        /// </summary>
        internal static string lblTelefonoEmpleado {
            get {
                return ResourceManager.GetString("lblTelefonoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo cliente.
        /// </summary>
        internal static string lblTipoClientes {
            get {
                return ResourceManager.GetString("lblTipoClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Licencia:.
        /// </summary>
        internal static string lblTipoLicencia {
            get {
                return ResourceManager.GetString("lblTipoLicencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de placa:.
        /// </summary>
        internal static string lblTipoPlaca {
            get {
                return ResourceManager.GetString("lblTipoPlaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de la unidad:.
        /// </summary>
        internal static string lblTipoUnidad {
            get {
                return ResourceManager.GetString("lblTipoUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo viaje:.
        /// </summary>
        internal static string lblTipoViaje {
            get {
                return ResourceManager.GetString("lblTipoViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de viaje:.
        /// </summary>
        internal static string lblTipoViajePrincipal {
            get {
                return ResourceManager.GetString("lblTipoViajePrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a último Kilimetraje:.
        /// </summary>
        internal static string lblUltimoK {
            get {
                return ResourceManager.GetString("lblUltimoK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad.
        /// </summary>
        internal static string lblUnidad {
            get {
                return ResourceManager.GetString("lblUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades.
        /// </summary>
        internal static string lblUnidades {
            get {
                return ResourceManager.GetString("lblUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades de transporte..
        /// </summary>
        internal static string lblUnidadestransporte {
            get {
                return ResourceManager.GetString("lblUnidadestransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad de Transporte:.
        /// </summary>
        internal static string lblUnidadTransporte {
            get {
                return ResourceManager.GetString("lblUnidadTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el usuario a recuperar:.
        /// </summary>
        internal static string lblUsuarioArecuperar {
            get {
                return ResourceManager.GetString("lblUsuarioArecuperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido!.
        /// </summary>
        internal static string lblUsuarioprincipal {
            get {
                return ResourceManager.GetString("lblUsuarioprincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string lblUsuariosmenu {
            get {
                return ResourceManager.GetString("lblUsuariosmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viaje:.
        /// </summary>
        internal static string lblViajeDirecciones {
            get {
                return ResourceManager.GetString("lblViajeDirecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viajes.
        /// </summary>
        internal static string lblViajes {
            get {
                return ResourceManager.GetString("lblViajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viajes Activos.
        /// </summary>
        internal static string lblViajesActivos {
            get {
                return ResourceManager.GetString("lblViajesActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viajes.
        /// </summary>
        internal static string lblViajesPrincipal {
            get {
                return ResourceManager.GetString("lblViajesPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VIN:.
        /// </summary>
        internal static string lblVIN {
            get {
                return ResourceManager.GetString("lblVIN", resourceCulture);
            }
        }
    }
}
