//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemGestionBuses.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemGestionBuses.Idiomas.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar y continuar.
        /// </summary>
        internal static string btnFinalizar {
            get {
                return ResourceManager.GetString("btnfinalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de confirmación.
        /// </summary>
        internal static string codigoconfir {
            get {
                return ResourceManager.GetString("codigoconfir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        internal static string confirmacion_contra {
            get {
                return ResourceManager.GetString("confirmacion_contra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña y PIN.
        /// </summary>
        internal static string contra_pin {
            get {
                return ResourceManager.GetString("contra_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string contrasena {
            get {
                return ResourceManager.GetString("contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string informacion {
            get {
                return ResourceManager.GetString("informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar datos.
        /// </summary>
        internal static string ingresadatos {
            get {
                return ResourceManager.GetString("ingresadatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        internal static string municipiolbl {
            get {
                return ResourceManager.GetString("municipiolbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidó  su contraseña?.
        /// </summary>
        internal static string olvido_contrasena {
            get {
                return ResourceManager.GetString("olvido_contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 1.
        /// </summary>
        internal static string paso1 {
            get {
                return ResourceManager.GetString("paso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string paso1btn {
            get {
                return ResourceManager.GetString("paso1btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el correo principal para gestionar el sistema.
        /// </summary>
        internal static string paso1lbl1 {
            get {
                return ResourceManager.GetString("paso1lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un nombre de usuario.
        /// </summary>
        internal static string paso1lbl2 {
            get {
                return ResourceManager.GetString("paso1lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 2.
        /// </summary>
        internal static string paso2 {
            get {
                return ResourceManager.GetString("paso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar código.
        /// </summary>
        internal static string paso2btn1 {
            get {
                return ResourceManager.GetString("paso2btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar código.
        /// </summary>
        internal static string paso2btn2 {
            get {
                return ResourceManager.GetString("paso2btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código de confirmación que se te envió al correo para confirmar la identidad.
        /// </summary>
        internal static string paso2lbl1 {
            get {
                return ResourceManager.GetString("paso2lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 3.
        /// </summary>
        internal static string paso3 {
            get {
                return ResourceManager.GetString("paso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string paso3btn {
            get {
                return ResourceManager.GetString("paso3btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener como mínimo 10 caracteres, con una combinación de letras y números. (Solo algunos simbolos son perimitidos ).
        /// </summary>
        internal static string paso3lbl1 {
            get {
                return ResourceManager.GetString("paso3lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 4.
        /// </summary>
        internal static string paso4 {
            get {
                return ResourceManager.GetString("paso4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string paso4btn {
            get {
                return ResourceManager.GetString("paso4btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el nombre de tu empresa, institución, emprendimiento o negocio..
        /// </summary>
        internal static string paso4lbl1 {
            get {
                return ResourceManager.GetString("paso4lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa la dirección donde se encuentra:.
        /// </summary>
        internal static string paso4lbl2 {
            get {
                return ResourceManager.GetString("paso4lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string phonelbl {
            get {
                return ResourceManager.GetString("phonelbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un PIN de seguridad. (Mínimo de 10 caracteres)..
        /// </summary>
        internal static string pinlabel {
            get {
                return ResourceManager.GetString("pinlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicar sesión.
        /// </summary>
        internal static string sesion {
            get {
                return ResourceManager.GetString("sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuario.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
    }
}
