//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemGestionBuses.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemGestionBuses.Idiomas.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Direccion.
        /// </summary>
        internal static string btnAgregarDireccion {
            get {
                return ResourceManager.GetString("btnAgregarDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Punto.
        /// </summary>
        internal static string btnAgregarPunto {
            get {
                return ResourceManager.GetString("btnAgregarPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar Viaje.
        /// </summary>
        internal static string BtnAsignarViaje {
            get {
                return ResourceManager.GetString("BtnAsignarViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Idioma:.
        /// </summary>
        internal static string btnCambiarIdioma {
            get {
                return ResourceManager.GetString("btnCambiarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string btnConfirmar {
            get {
                return ResourceManager.GetString("btnConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string btnconfirmarcontraseñaLocus {
            get {
                return ResourceManager.GetString("btnconfirmarcontraseñaLocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string btnConfirmarPINLocus {
            get {
                return ResourceManager.GetString("btnConfirmarPINLocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Punto.
        /// </summary>
        internal static string btnEliminarPunto {
            get {
                return ResourceManager.GetString("btnEliminarPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        internal static string btnFinalizar {
            get {
                return ResourceManager.GetString("btnFinalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Rutas.
        /// </summary>
        internal static string btnGenerarRutas {
            get {
                return ResourceManager.GetString("btnGenerarRutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string btnIniciarSesion {
            get {
                return ResourceManager.GetString("btnIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Campos.
        /// </summary>
        internal static string btnLimpiarCampos {
            get {
                return ResourceManager.GetString("btnLimpiarCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar código.
        /// </summary>
        internal static string btnReenviar {
            get {
                return ResourceManager.GetString("btnReenviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Idioma:.
        /// </summary>
        internal static string btnSeleccionarIdioma {
            get {
                return ResourceManager.GetString("btnSeleccionarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignación de viajes..
        /// </summary>
        internal static string lblAsignaciondeViaje {
            get {
                return ResourceManager.GetString("lblAsignaciondeViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controla las acciones que te han sido asignadas a través de este panel de control..
        /// </summary>
        internal static string lblBienvenido {
            get {
                return ResourceManager.GetString("lblBienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a Locus System.
        /// </summary>
        internal static string lblBienvenidoLocus {
            get {
                return ResourceManager.GetString("lblBienvenidoLocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente:.
        /// </summary>
        internal static string lblCliente {
            get {
                return ResourceManager.GetString("lblCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string lblClientes {
            get {
                return ResourceManager.GetString("lblClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de confirmación.
        /// </summary>
        internal static string lblCodConfirmacion {
            get {
                return ResourceManager.GetString("lblCodConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de confirmación que se te enció al correo para confirmar la identidad..
        /// </summary>
        internal static string lblCodigo {
            get {
                return ResourceManager.GetString("lblCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1- Cambia tu Contraseña.
        /// </summary>
        internal static string lblConfigurarContraseña {
            get {
                return ResourceManager.GetString("lblConfigurarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, configura tu perfil antes de iniciar sesión.
        /// </summary>
        internal static string lblconfigurarPerfil {
            get {
                return ResourceManager.GetString("lblconfigurarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2- Configura tu pin de seguridad.
        /// </summary>
        internal static string lblConfigurarPIN {
            get {
                return ResourceManager.GetString("lblConfigurarPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de contraseña:.
        /// </summary>
        internal static string lblConfirmacionContra {
            get {
                return ResourceManager.GetString("lblConfirmacionContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lblContraseña {
            get {
                return ResourceManager.GetString("lblContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contenercomo mínimo 10 caracteres, con una combinación de letras y números. (Solo algunos símbolos son permitidos).
        /// </summary>
        internal static string lblContraseñaCondiciones {
            get {
                return ResourceManager.GetString("lblContraseñaCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string lblContraseñaUsuario {
            get {
                return ResourceManager.GetString("lblContraseñaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña y PIN.
        /// </summary>
        internal static string lblContraseñayPin {
            get {
                return ResourceManager.GetString("lblContraseñayPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el correo principal para gestionar el sistema.
        /// </summary>
        internal static string lblcorreo {
            get {
                return ResourceManager.GetString("lblcorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino adicional:.
        /// </summary>
        internal static string lblDestinoAdicional {
            get {
                return ResourceManager.GetString("lblDestinoAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino final del viaje:.
        /// </summary>
        internal static string lblDestinoFinalViaje {
            get {
                return ResourceManager.GetString("lblDestinoFinalViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa la dirección donde se encuentra:.
        /// </summary>
        internal static string lblDireccion {
            get {
                return ResourceManager.GetString("lblDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección adicional:.
        /// </summary>
        internal static string lblDireccionAdicional {
            get {
                return ResourceManager.GetString("lblDireccionAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección final:.
        /// </summary>
        internal static string lblDireccionFinal {
            get {
                return ResourceManager.GetString("lblDireccionFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DUI:.
        /// </summary>
        internal static string lblDUI {
            get {
                return ResourceManager.GetString("lblDUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        internal static string lblEmpleados {
            get {
                return ResourceManager.GetString("lblEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el nombre de tu empresa, institución, emprendimiento o negocio..
        /// </summary>
        internal static string lblEmpresa {
            get {
                return ResourceManager.GetString("lblEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string lblInformacion {
            get {
                return ResourceManager.GetString("lblInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa los datos.
        /// </summary>
        internal static string lblIngresaDatos {
            get {
                return ResourceManager.GetString("lblIngresaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa las direcciones:.
        /// </summary>
        internal static string lblIngresaDirecciones {
            get {
                return ResourceManager.GetString("lblIngresaDirecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia Sesión.
        /// </summary>
        internal static string lblIniciarSesion {
            get {
                return ResourceManager.GetString("lblIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud:.
        /// </summary>
        internal static string lblLatitud {
            get {
                return ResourceManager.GetString("lblLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        internal static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud:.
        /// </summary>
        internal static string lblLongitud {
            get {
                return ResourceManager.GetString("lblLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimientos.
        /// </summary>
        internal static string lblMantenimientos {
            get {
                return ResourceManager.GetString("lblMantenimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        internal static string lblMunicipio {
            get {
                return ResourceManager.GetString("lblMunicipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NIT:.
        /// </summary>
        internal static string lblNIT {
            get {
                return ResourceManager.GetString("lblNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un nombre de usuario.
        /// </summary>
        internal static string lblNombreUsuario {
            get {
                return ResourceManager.GetString("lblNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del viaje:.
        /// </summary>
        internal static string lblNombreViaje {
            get {
                return ResourceManager.GetString("lblNombreViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ó.
        /// </summary>
        internal static string lblO {
            get {
                return ResourceManager.GetString("lblO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 1.
        /// </summary>
        internal static string lblPaso1 {
            get {
                return ResourceManager.GetString("lblPaso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 2.
        /// </summary>
        internal static string lblPaso2 {
            get {
                return ResourceManager.GetString("lblPaso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 3.
        /// </summary>
        internal static string lblPaso3 {
            get {
                return ResourceManager.GetString("lblPaso3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 4.
        /// </summary>
        internal static string lblPaso4 {
            get {
                return ResourceManager.GetString("lblPaso4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un PIN de seguridad. (Mínimo de 10 caracteres)..
        /// </summary>
        internal static string lblPINseguridad {
            get {
                return ResourceManager.GetString("lblPINseguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto de partida:.
        /// </summary>
        internal static string lblPuntodePartida {
            get {
                return ResourceManager.GetString("lblPuntodePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto de referencia:.
        /// </summary>
        internal static string lblPuntoReferencia {
            get {
                return ResourceManager.GetString("lblPuntoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recupera tu contraseña.
        /// </summary>
        internal static string lblRecuperarContra {
            get {
                return ResourceManager.GetString("lblRecuperarContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        internal static string lblReportes {
            get {
                return ResourceManager.GetString("lblReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona el viaje que deseas asignarle al cliente..
        /// </summary>
        internal static string lblSeleccionViaje {
            get {
                return ResourceManager.GetString("lblSeleccionViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarifa:.
        /// </summary>
        internal static string lblTarifa {
            get {
                return ResourceManager.GetString("lblTarifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string lblTeléfono {
            get {
                return ResourceManager.GetString("lblTeléfono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo viaje:.
        /// </summary>
        internal static string lblTipoViaje {
            get {
                return ResourceManager.GetString("lblTipoViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades.
        /// </summary>
        internal static string lblUnidades {
            get {
                return ResourceManager.GetString("lblUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido!.
        /// </summary>
        internal static string lblUsuarioprincipal {
            get {
                return ResourceManager.GetString("lblUsuarioprincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string lblUsuariosmenu {
            get {
                return ResourceManager.GetString("lblUsuariosmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viaje:.
        /// </summary>
        internal static string lblViajeDirecciones {
            get {
                return ResourceManager.GetString("lblViajeDirecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viajes.
        /// </summary>
        internal static string lblViajes {
            get {
                return ResourceManager.GetString("lblViajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viajes Activos.
        /// </summary>
        internal static string lblViajesActivos {
            get {
                return ResourceManager.GetString("lblViajesActivos", resourceCulture);
            }
        }
    }
}
